from django.urls import path
from django.views.generic import TemplateView

from . import views

INDEXNOW_KEY = (
    "a94d996aed18be0932540221541260e95651607e49a7bbc46deecc9dbe788b35"
)

urlpatterns = [
    path('health/', views.health, name="health"),
    path(
        f'{INDEXNOW_KEY}.txt',
        TemplateView.as_view(
            template_name=f'{INDEXNOW_KEY}.txt',
            content_type='text/plain; charset=utf-8',
        ),
        name="indexnow_key",
    ),
    path('robots.txt', views.robots_txt, name="robots_txt"),
    path('sitemap.xml', views.sitemap_xml, name="sitemap_xml"),
    path('pricing/', views.pricing, name="pricing"),
    path('contact/', views.contact, name="contact"),
    path('faq/', views.faq, name="faq"),
    path('privacy/', views.privacy, name="privacy"),
    path('terms/', views.terms, name="terms"),
    path('guides/', views.guide_library, name="guide_library"),
    path(
        'first-experiment/',
        views.first_experiment,
        name="first_experiment",
    ),
    path(
        'demo/sodium-chlorine/',
        views.sodium_chlorine_demo,
        name="sodium_chlorine_demo",
    ),
    path(
        'demo/carbon-dioxide-calcium-hydroxide/',
        views.prepared_reaction_demo,
        {'demo_key': 'carbon-dioxide-calcium-hydroxide'},
        name="demo_carbon_dioxide_calcium_hydroxide",
    ),
    path(
        'demo/sodium-carbonate-hydrochloric-acid/',
        views.prepared_reaction_demo,
        {'demo_key': 'sodium-carbonate-hydrochloric-acid'},
        name="demo_sodium_carbonate_hydrochloric_acid",
    ),
    path(
        'demo/silver-nitrate-potassium-iodide/',
        views.prepared_reaction_demo,
        {'demo_key': 'silver-nitrate-potassium-iodide'},
        name="demo_silver_nitrate_potassium_iodide",
    ),
    path(
        'demo/copper-sulfate-potassium-hydroxide/',
        views.prepared_reaction_demo,
        {'demo_key': 'copper-sulfate-potassium-hydroxide'},
        name="demo_copper_sulfate_potassium_hydroxide",
    ),
    path(
        'demo/sodium-water/',
        views.prepared_reaction_demo,
        {'demo_key': 'sodium-water'},
        name="demo_sodium_water",
    ),
    path(
        'demo/zinc-hydrochloric-acid/',
        views.prepared_reaction_demo,
        {'demo_key': 'zinc-hydrochloric-acid'},
        name="demo_zinc_hydrochloric_acid",
    ),
    path(
        'demo/acetic-acid-sodium-bicarbonate/',
        views.prepared_reaction_demo,
        {'demo_key': 'acetic-acid-sodium-bicarbonate'},
        name="demo_acetic_acid_sodium_bicarbonate",
    ),
    path(
        'demo/hydrogen-oxygen/',
        views.prepared_reaction_demo,
        {'demo_key': 'hydrogen-oxygen'},
        name="demo_hydrogen_oxygen",
    ),
    path(
        'demo/iron-oxygen/',
        views.prepared_reaction_demo,
        {'demo_key': 'iron-oxygen'},
        name="demo_iron_oxygen",
    ),
    path(
        'demo/copper-oxygen/',
        views.prepared_reaction_demo,
        {'demo_key': 'copper-oxygen'},
        name="demo_copper_oxygen",
    ),
    path(
        'demo/potassium-permanganate-hydrogen-peroxide/',
        views.prepared_reaction_demo,
        {'demo_key': 'potassium-permanganate-hydrogen-peroxide'},
        name="demo_potassium_permanganate_hydrogen_peroxide",
    ),
    path(
        'demo/sodium-chloride-water/',
        views.prepared_reaction_demo,
        {'demo_key': 'sodium-chloride-water'},
        name="demo_sodium_chloride_water",
    ),
    path(
        'demo/carbon-dioxide-sodium-hydroxide/',
        views.prepared_reaction_demo,
        {'demo_key': 'carbon-dioxide-sodium-hydroxide'},
        name="demo_carbon_dioxide_sodium_hydroxide",
    ),
    path(
        'demo/hydrochloric-acid-sodium-hydroxide/',
        views.prepared_reaction_demo,
        {'demo_key': 'hydrochloric-acid-sodium-hydroxide'},
        name="demo_hydrochloric_acid_sodium_hydroxide",
    ),
    path(
        'demo/silver-nitrate-sodium-chloride/',
        views.prepared_reaction_demo,
        {'demo_key': 'silver-nitrate-sodium-chloride'},
        name="demo_silver_nitrate_sodium_chloride",
    ),
    path(
        'demo/carbon-monoxide-oxygen/',
        views.prepared_reaction_demo,
        {'demo_key': 'carbon-monoxide-oxygen'},
        name="demo_carbon_monoxide_oxygen",
    ),
    path(
        'demo/carbon-dioxide-water/',
        views.prepared_reaction_demo,
        {'demo_key': 'carbon-dioxide-water'},
        name="demo_carbon_dioxide_water",
    ),
    path(
        'demo/nitrogen-dioxide-water/',
        views.prepared_reaction_demo,
        {'demo_key': 'nitrogen-dioxide-water'},
        name="demo_nitrogen_dioxide_water",
    ),
    path(
        'demo/hydrogen-chlorine/',
        views.prepared_reaction_demo,
        {'demo_key': 'hydrogen-chlorine'},
        name="demo_hydrogen_chlorine",
    ),
    path(
        'demo/carbon-oxygen/',
        views.prepared_reaction_demo,
        {'demo_key': 'carbon-oxygen'},
        name="demo_carbon_oxygen",
    ),
    path(
        'demo/iron-hydrochloric-acid/',
        views.prepared_reaction_demo,
        {'demo_key': 'iron-hydrochloric-acid'},
        name="demo_iron_hydrochloric_acid",
    ),
    path(
        'guides/sodium-and-chlorine-reaction/',
        views.guided_experiment,
        {'guide_key': 'reaction'},
        name="guide_sodium_chlorine_reaction",
    ),
    path(
        'guides/sodium-and-chlorine-formula/',
        views.guided_experiment,
        {'guide_key': 'formula'},
        name="guide_sodium_chlorine_formula",
    ),
    path(
        'guides/sodium-and-chlorine-ionic-bond/',
        views.guided_experiment,
        {'guide_key': 'ionic-bond'},
        name="guide_sodium_chlorine_ionic_bond",
    ),
    path(
        'guides/chemical-reaction-virtual-lab/',
        views.chemical_reaction_virtual_lab,
        name="chemical_reaction_virtual_lab",
    ),
    path(
        'guides/why-limewater-turns-cloudy-with-carbon-dioxide/',
        views.observation_guide,
        {'guide_key': 'limewater-carbon-dioxide'},
        name="guide_limewater_carbon_dioxide",
    ),
    path(
        'guides/why-sodium-carbonate-fizzes-with-hydrochloric-acid/',
        views.observation_guide,
        {'guide_key': 'sodium-carbonate-hydrochloric-acid'},
        name="guide_sodium_carbonate_hydrochloric_acid",
    ),
    path(
        'guides/silver-nitrate-potassium-iodide-precipitate/',
        views.observation_guide,
        {'guide_key': 'silver-nitrate-potassium-iodide'},
        name="guide_silver_nitrate_potassium_iodide",
    ),
    path(
        'guides/copper-ii-sulfate-potassium-hydroxide-precipitate/',
        views.observation_guide,
        {'guide_key': 'copper-sulfate-potassium-hydroxide'},
        name="guide_copper_sulfate_potassium_hydroxide",
    ),
    path(
        'guides/reaction-of-sodium-in-water/',
        views.observation_guide,
        {'guide_key': 'sodium-water'},
        name="guide_sodium_water",
    ),
    path(
        'guides/zinc-and-hydrochloric-acid-reaction/',
        views.observation_guide,
        {'guide_key': 'zinc-hydrochloric-acid'},
        name="guide_zinc_hydrochloric_acid",
    ),
    path(
        'guides/acetic-acid-and-sodium-bicarbonate-reaction/',
        views.observation_guide,
        {'guide_key': 'acetic-acid-sodium-bicarbonate'},
        name="guide_acetic_acid_sodium_bicarbonate",
    ),
    path(
        'guides/hydrogen-and-oxygen-reaction/',
        views.observation_guide,
        {'guide_key': 'hydrogen-oxygen'},
        name="guide_hydrogen_oxygen",
    ),
    path(
        'guides/reaction-of-iron-with-oxygen/',
        views.observation_guide,
        {'guide_key': 'iron-oxygen'},
        name="guide_iron_oxygen",
    ),
    path(
        'guides/reaction-of-copper-with-oxygen/',
        views.observation_guide,
        {'guide_key': 'copper-oxygen'},
        name="guide_copper_oxygen",
    ),
    path(
        'guides/potassium-permanganate-and-hydrogen-peroxide-reaction/',
        views.observation_guide,
        {'guide_key': 'potassium-permanganate-hydrogen-peroxide'},
        name="guide_potassium_permanganate_hydrogen_peroxide",
    ),
    path(
        'guides/sodium-chloride-and-water-reaction/',
        views.observation_guide,
        {'guide_key': 'sodium-chloride-water'},
        name="guide_sodium_chloride_water",
    ),
    path(
        'guides/carbon-dioxide-and-sodium-hydroxide-reaction/',
        views.observation_guide,
        {'guide_key': 'carbon-dioxide-sodium-hydroxide'},
        name="guide_carbon_dioxide_sodium_hydroxide",
    ),
    path(
        'guides/hydrochloric-acid-and-sodium-hydroxide-reaction/',
        views.observation_guide,
        {'guide_key': 'hydrochloric-acid-sodium-hydroxide'},
        name="guide_hydrochloric_acid_sodium_hydroxide",
    ),
    path(
        'guides/silver-nitrate-and-sodium-chloride-reaction/',
        views.observation_guide,
        {'guide_key': 'silver-nitrate-sodium-chloride'},
        name="guide_silver_nitrate_sodium_chloride",
    ),
    path(
        'guides/carbon-monoxide-and-oxygen-reaction/',
        views.observation_guide,
        {'guide_key': 'carbon-monoxide-oxygen'},
        name="guide_carbon_monoxide_oxygen",
    ),
    path(
        'guides/carbon-dioxide-and-water-reaction/',
        views.observation_guide,
        {'guide_key': 'carbon-dioxide-water'},
        name="guide_carbon_dioxide_water",
    ),
    path(
        'guides/nitrogen-dioxide-and-water-reaction/',
        views.observation_guide,
        {'guide_key': 'nitrogen-dioxide-water'},
        name="guide_nitrogen_dioxide_water",
    ),
    path(
        'guides/hydrogen-and-chlorine-reaction/',
        views.observation_guide,
        {'guide_key': 'hydrogen-chlorine'},
        name="guide_hydrogen_chlorine",
    ),
    path(
        'guides/carbon-and-oxygen-reaction/',
        views.observation_guide,
        {'guide_key': 'carbon-oxygen'},
        name="guide_carbon_oxygen",
    ),
    path(
        'guides/iron-and-hydrochloric-acid-reaction/',
        views.observation_guide,
        {'guide_key': 'iron-hydrochloric-acid'},
        name="guide_iron_hydrochloric_acid",
    ),
    path('ai_insights/', views.ai_insights, name="ai_insights"),
]
